 echo "DXライブラリのセットアップを始めます!!"
 echo "DXライブラリのダウンロードを始めます!!"
 Invoke-WebRequest -Uri "https://dxlib.xsrv.jp/DxLib/DxLib_GCC3_22c.zip" -OutFile "dxlib.zip"
 echo "DXライブラリの解凍を始めます!!"
 Expand-Archive -Path "dxlib.zip" -DestinationPath "."
 New-Item -Path "7_3_0" -ItemType Directory
 Copy-Item ".\DxLib_GCC\プロジェクトに追加すべきファイル_GCC(MinGW)用\7_3_0_x86_64_w64_win32_seh_rt_v5_rev0\*"  -Destination "./7_3_0"
 Remove-Item -Recurse -Path "DxLib_GCC"
 Remove-Item "dxlib.zip"
 echo "セットアップ終わったよ!!"
 echo "プログラミングがんばれ!!"